SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE logistimo.COUNTRY MODIFY COLUMN ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;


SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE logistimo.STATE MODIFY COLUMN ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;


SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE logistimo.DISTRICT MODIFY COLUMN ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;


SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE logistimo.SUBDISTRICT MODIFY COLUMN ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;
