ALTER TABLE logistimo.KIOSK ADD COLUMN COUNTRYID INT NULL, STATEID INT NULL, DISTID INT NULL, SUBDISTID INT NULL, PLACEID INT NULL;

ALTER TABLE logistimo.USERACCOUNT ADD COLUMN COUNTRYID INT NULL, STATEID INT NULL, DISTID INT NULL, SUBDISTID INT NULL, PLACEID INT NULL;
