--liquibase formatted sql
--changeset kumargaurav:locationservice.location.sql

CREATE TABLE IF NOT EXISTS `logistimo`.`COUNTRY` (
  `ID` INT NOT NULL,
  `COUNTRYNAME` VARCHAR(50) NOT NULL,
  `COUNTRYCODE` VARCHAR(20) NULL,
  `CREATEDBY` VARCHAR(50) NULL,
  `CREATEDON` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `COUNTRY_NAME_UNIQUE` (`COUNTRYNAME` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logistimo`.`STATE` (
  `ID` INT NOT NULL,
  `STATENAME` VARCHAR(50) NOT NULL,
  `STATECODE` VARCHAR(20) NULL,
  `COUNTRYID` INT NOT NULL,
  `CREATEDBY` VARCHAR(45) NULL,
  `CREATEDON` DATETIME NULL,
  PRIMARY KEY (`ID`, `COUNTRYID`),
  INDEX `ID_idx` (`COUNTRYID` ASC),
  CONSTRAINT `ID`
    FOREIGN KEY (`COUNTRYID`)
    REFERENCES `logistimo`.`COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logistimo`.`DISTRICT` (
  `ID` INT NOT NULL,
  `DISTNAME` VARCHAR(50) NOT NULL,
  `DISTCODE` VARCHAR(45) NULL,
  `STATEID` INT NULL,
  `CREATEDBY` VARCHAR(45) NULL,
  `CREATEDON` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `SID`
    FOREIGN KEY (`STATEID`)
    REFERENCES `logistimo`.`STATE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logistimo`.`SUBDISRICT` (
  `ID` INT NOT NULL,
  `SUBDISNAME` VARCHAR(100) NULL,
  `TYPE` ENUM('TEHSIL', 'BLOCK') NULL,
  `DISTID` INT NULL,
  `CREATEDBY` VARCHAR(45) NULL,
  `CREATEDON` DATETIME NULL,
  `STATEID` INT NULL,
  `COUNTRYID` INT NULL,
  `PARENTID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`DISTID` ASC),
  INDEX `ID_idx1` (`PARENTID` ASC),
  CONSTRAINT `DID`
    FOREIGN KEY (`DISTID`)
    REFERENCES `logistimo`.`DISTRICT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRID`
    FOREIGN KEY (`PARENTID`)
    REFERENCES `logistimo`.`SUBDISRICT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logistimo`.`PLACE` (
  `ID` INT NOT NULL,
  `PLACENAME` VARCHAR(45) NULL,
  `PLACECODE` VARCHAR(45) NULL,
  `CRAETEDBY` VARCHAR(45) NULL,
  `CREATEDON` DATETIME NULL,
  `TYPE` ENUM('CITY', 'VILLAGE') NULL,
  `LONGITUDE` DECIMAL(10,6) NULL,
  `LATITUDE` DECIMAL(10,6) NULL,
  `TYPEREF` INT NULL,
  `POSTALCODE` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `logistimo`.`ADDRESS` (
  `ID` INT NOT NULL,
  `STREET` VARCHAR(200) NULL,
  `STREETEXT` VARCHAR(200) NULL,
  `PLACEID` INT NULL,
  `COUNTRYID` INT NULL,
  `POSTALCODE` INT NULL,
  `LONGITUDE` DECIMAL(10,6) NULL,
  `LATITUDE` DECIMAL(10,6) NULL,
  `STATEID` INT NULL,
  `DISTTID` INT NULL,
  `SUBDISTID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`PLACEID` ASC),
  INDEX `ID_idx1` (`STATEID` ASC),
  INDEX `ID_idx2` (`COUNTRYID` ASC),
  CONSTRAINT `PLID`
    FOREIGN KEY (`PLACEID`)
    REFERENCES `logistimo`.`SUBDISRICT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `STID`
    FOREIGN KEY (`STATEID`)
    REFERENCES `logistimo`.`STATE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CID`
    FOREIGN KEY (`COUNTRYID`)
    REFERENCES `logistimo`.`COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
